var epbjs=epbjs||{};epbjs.que=epbjs.que||[];epbjs.ezAdUnits=epbjs.ezAdUnits||[];epbjs.ezdss=epbjs.ezdss||[];epbjs.ezas=epbjs.ezas||[];epbjs.ezobid=epbjs.ezobid||[];window.ezoptbid=window.ezoptbid||[];epbjs.que.push(function(){epbjs.onEvent('adRenderSucceeded',function(e){var slot=getSlotForhb(e.bid.adUnitCode);var ic=slot.getTargeting('ic')[0];if(typeof ic!=='undefined'){ic=parseInt(ic);__ez.pel.Add(slot,[(new __ezDotData('refresh_count',ic))]);}
var ebbr=e.slot.getTargeting('eb_br');if(typeof ebbr!='undefined'){__ez.pel.Add(slot,[(new __ezDotData('filled_bid_hash',ebbr))]);}
if(typeof epbjs.SS[e.bid.bidder.toLowerCase()]!=="undefined"){var last_bid_val=0;if(typeof slot.getTargeting("lb")[0]!="undefined"){last_bid_val=parseInt(slot.getTargeting("lb")[0])/100000.0;}
__ez.pel.Add(slot,[(new __ezDotData("stat_source_id",epbjs.SS[e.bid.bidder.toLowerCase()]))],e.bid.cpm/1000,0,e.bid.cpm/1000,last_bid_val,epbjs.SS[e.bid.bidder.toLowerCase()]);}
var media_type=slot.getTargeting("hb_format");var prebid_source=slot.getTargeting("hb_rt");if(typeof media_type!==undefined&&media_type.length>0&&String(media_type[0])!==""){var media_type_str=String(media_type[0]);__ez.pel.Add(slot,[(new __ezDotData("media_type",media_type_str))]);}
if(typeof prebid_source!==undefined&&prebid_source.length>0&&String(prebid_source[0])!==""){var prebid_source_str=String(prebid_source[0]);__ez.pel.Add(slot,[(new __ezDotData("prebid_source",prebid_source_str))]);}
__ez.pel.Add(slot,[(new __ezDotData("loaded",1))],e.bid.cpm/1000,0,e.bid.cpm/1000,last_bid_val,epbjs.SS[e.bid.bidder.toLowerCase()]);if(typeof window.ezbfcr!=='undefined'||typeof window.ezbflclcr!=='undefined'){__ez.pel.Add(slot,[(new __ezDotData("bid_floor_local_dfp",bid_val_raw))]);__ez.pel.Add(slot,[(new __ezDotData("bid_floor_local_adx",bid_val_lcl))]);}
__ez.pel.Fire();});if(__enableAnalytics==true){epbjs.enableAnalytics([{provider:"ga",options:{trackerName:"gatestprebid"}}]);}
const consentManagement={usp:{cmpApi:'iab',timeout:100}}
if(typeof window.__tcfapi==="function"){consentManagement.gdpr={cmpApi:'iab',timeout:8000,}}
var priceBuckets={};if(window.ezhbopt===true){priceBuckets.buckets=[{"precision":2,"min":0,"max":300,"increment":0.01}]}else{priceBuckets.buckets=[{"precision":2,"min":0,"max":5,"increment":0.01},{"precision":2,"min":5,"max":50,"increment":0.10},{"precision":2,"min":50,"max":120,"increment":5.00}]}
epbjs.aliasBidder('aol','onedisplay');epbjs.aliasBidder('aol','onemobile');var schain_domain='ezoic.ai';var dom='';if(typeof __ez_nid!='undefined'&&__ez_nid==21732118914){schain_domain='ezoic.co.uk';}
if(typeof location.host!='undefined'){dom=location.host}
var useCache=false;if(typeof window.ezpbCache!='undefined'){useCache=true;}
var userIdList=[{name:"criteo"},{name:"unifiedId",params:{url:"//match.adsrvr.org/track/rid?ttd_pid=muno13d&fmt=json"},storage:{type:"cookie",name:"pbjs-unifiedid",expires:60}},{name:"quantcastId"},{name:"amxId",storage:{name:"amxId",type:"html5",expires:1,}},{name:"pubCommonId",params:{pixelUrl:"/wp-json/pubcid/v1/extend/"},storage:{type:"cookie",name:"_pubcid",expires:365}},{name:"lotamePanoramaId",}]
var id5={name:"id5Id",params:{partner:457,},storage:{type:"html5",name:"id5id",expires:90,refreshInSeconds:8*3600}}
if(typeof __pd!=='undefined'){id5.params.pd=__pd;}
userIdList.push(id5);epbjs.setConfig({useBidCache:useCache,s2sConfig:{accountId:'1',bidders:__s2sbidders,timeout:2000,enabled:true,endpoint:'https://pb-server.ezoic.com/openrtb2/auction',syncEndpoint:'https://pb-server.ezoic.com/cookie_sync',extPrebid:{aliases:{"viewdeosDX":"viewdeos"}}},schain:{validation:"strict",config:{ver:"1.0",complete:1,nodes:[{asi:schain_domain,sid:__sellerid,domain:dom,hp:1}]}},priceGranularity:priceBuckets,userSync:{userIds:userIdList,filterSettings:{iframe:{bidders:__allBidders,filter:'include'},image:{bidders:['luponmedia'],filter:'include'}},syncDelay:3000,aliasSyncEnabled:true},consentManagement:consentManagement});epbjs.bidderSettings=epbjs.bidderSettings||{};epbjs.bidderSettings["standard"]={adserverTargeting:[{key:"epb",val:function(bidResponse){return bidResponse.bidderCode;}},{key:"epa",val:function(bidResponse){return bidResponse.adId;}},{key:"epp",val:function(bidResponse){return bidResponse.pbCg;}},{key:"epf",val:function(bidResponse){return bidResponse.mediaType;}},{key:"eps",val:function(bidResponse){if(bidResponse.bidder=="ehb"){return 0;}
if(typeof epbjs.SS[bidResponse.bidder.toLowerCase()]!=="undefined"){return epbjs.SS[bidResponse.bidder.toLowerCase()];}else if(typeof epbjs.SS[bidResponse.bidder]!=="undefined"){return epbjs.SS[bidResponse.bidder];}else{console.error("epbjs: NO MATCH");return 0;}}},{key:"epr",val:function(bidResponse){return bidResponse.source;}}]};epbjs.bidderSettings["criteo"]={storageAllowed:true};epbjs.onEvent('bidResponse',function(e){window.ezosethbbid(e);});epbjs.onEvent('bidWon',function(bid){epbjs.ezas[bid.adUnitCode]=bid.size;if(bid.bidder=="ehb"){epbjs.ezdss[bid.adUnitCode]=bid.ss;}else{if(typeof epbjs.SS[bid.bidder.toLowerCase()]!=="undefined"){epbjs.ezdss[bid.adUnitCode]=epbjs.SS[bid.bidder.toLowerCase()];if(epbjs.useAdj==true&&epbjs.bidders.indexOf(bid.bidder)>-1){epbjs.ezobid[bid.adUnitCode]=bid.cpm/epbjs.gadj;}}else if(typeof epbjs.SS[bid.bidder]!=="undefined"){epbjs.ezdss[bid.adUnitCode]=epbjs.SS[bid.bidder];if(epbjs.useAdj==true&&epbjs.bidders.indexOf(bid.bidder)>-1){epbjs.ezobid[bid.adUnitCode]=bid.cpm/epbjs.gadj;}}else{console.error("epbjs: NO MATCH");}}});});function getSlotForhb(adUnit){for(slot in window.ezslots){if(window[window.ezslots[slot]].getSlotElementId()==adUnit){return window[window.ezslots[slot]];}}}
function epbjsRequestAdUnits(adUnits){epbjs.que.push(function(){for(var i=0;i<adUnits.length;i++){epbjs.ezAdUnits.push(adUnits[i]);}
epbjs.addAdUnits(adUnits);epbjs.requestBids({bidsBackHandler:function(bidResponses){if(typeof window.ezosethbbids=="function"){window.ezosethbbids(bidResponses);}else{window.ezosethbbidsInterval=setInterval(function(bidResponses){if(typeof ezosethbbids=='function'){ezosethbbids(bidResponses);}},130,bidResponses);}}});});}
function epbjsRefreshSlot(slot){epbjs.que.push(function(){epbjs.requestBids({adUnitCodes:[slot.getSlotElementId()],bidsBackHandler:function(bidResponses){epbjs.fastLoadAuctionEnd=true;window.ezosethbbids(bidResponses);}});});}