(function(){if("object"!=typeof window._tct){window._tct=[];var f={protocol:"https:",host:"//www.trendcounter.com",h:"https://www.trendcounter.com",version:3,l:{"default":{}},a:{"default":{key:!1,title:"trendcounter Web Analytics",www:"leave",url:"full",cookie_domain:!1,use_cookies:!0,respect_dnt:!0,hide_feedback:!1,fb_attached:!1,parsed:0}},g:{stack:[],ready:!1},G:function(a){this.A();for(var b=0;b<window._tcq.length;b++){a=window._tcq[b];var c=this.o(a);if("object"!=typeof this.a[c.b]){this.a[c.b]=
{};this.l[c.b]={};for(var d in this.a["default"])this.a[c.b][d]=this.a["default"][d]}"www"==c.action&&"strip"==a[1]?this.a[c.b].www="strip":"url"==c.action&&this.j(a[1])?this.a[c.b].url=a[1]:"domain"==c.action&&0<=a[1].indexOf(".")?this.a[c.b].cookie_domain=a[1]:"init"==c.action?this.a[c.b].key=a[1]:"use_cookies"==c.action?this.a[c.b].use_cookies=a[1]:"respect_dnt"==c.action?this.a[c.b].respect_dnt=a[1]:"hide_feedback"==c.action&&1==a[1]&&(this.a[c.b].hide_feedback=!0);!1===this.a[c.b].cookie_domain&&
(this.a[c.b].cookie_domain="."+location.hostname.replace(/^www\./i,""))}},track:function(a,b){if("object"!=typeof this.a[a]||!1===this.a[a].key||this.B("_tc_"+this.a[a].key+"_z"))return!1;var c=!1;f.j(b[1])&&(this.a[a].url=b[1]);f.j(b[2])&&(c=b[2]);var d=navigator.language||navigator.userLanguage,d=d.split("-")[0].toLowerCase();try{0<=window.location.href.indexOf("tcSetup")&&this.m(function(){var b=document.createElement("div");b.style="font-family:Sans;font-size:14px;line-height:20px;padding: 18px 22px;background: #3D444C;color:#c2cad2;width: 300px;border-radius: 6px;box-shadow: 0 0 50px rgba(0, 0, 0, 0.5);position: fixed;top:20px;left:20px";
b.innerHTML="de"==d?b.innerHTML+('<b>trendcounter wurde korrekt installiert</b><br>Betrachte jetzt <a href="'+f.h+"/report/"+f.a[a].key+'/" style="color:#c2cad2;text-decoration:underline;">deine Statistiken.</a>'):b.innerHTML+('<b>trendcounter installation verified</b><br>View <a href="'+f.h+"/report/"+f.a[a].key+'/" style="color:#c2cad2;">your Statistics</a> now.');document.getElementsByTagName("body")[0].appendChild(b)})}catch(m){}this.c(a,"v",this.version);this.c(a,"o",location.protocol+"//"+location.hostname+
(location.port?":"+location.port:""));var e=0;!1!==this.B("_tc_"+this.a[a].key+"_a")&&(e=1);var l="yes"==navigator.doNotTrack||"1"==navigator.doNotTrack||"1"==navigator.msDoNotTrack;0==this.a[a].respect_dnt&&(l=!1);0==l&&1==this.a[a].use_cookies&&this.D(a);this.c(a,"l",d);this.O(a);this.N(a);this.c(a,"k",e);this.P(a);e=document.title;!1!==c?this.c(a,"t",c.substr(0,100)):e&&this.c(a,"t",e.substr(0,100));this.c(a,"z",this.random());this.L(a)},D:function(a){this.M("_tc_"+this.a[a].key+"_a",this.F(this.a[a].cookie_domain)+
"."+Math.floor((new Date).getTime()/1E3),31536E3,this.a[a].cookie_domain)},random:function(){return Math.round(2147483647*Math.random())},c:function(a,b,c){this.l[a][b]=c},C:function(a){var b="",c;for(c in this.l[a])b+=encodeURIComponent(c)+"="+encodeURIComponent(this.l[a][c])+"&";return b.substr(0,b.length-1)},N:function(a){var b;try{document.referrer&&(b=document.referrer)}catch(c){}try{"object"==typeof top.document&&(b=top.document.referrer)}catch(c){}b=b.replace(/^https?:\/\//,"http://");b=b.substr(0,
250);this.c(a,"r",b)},O:function(a){0<screen.width&&0<screen.height&&(this.c(a,"w",screen.width),this.c(a,"h",screen.height))},P:function(a){var b="",c=this.a[a].url,d=window.location;if("strip"==c)b=d.protocol+d.host+d.pathname;else if("full"==c)b=d.href;else if("canonical"==c)for(tags=document.getElementsByTagName("link"),g=0;g<tags.length;g++){if("canonical"==tags[g].rel){b=tags[g].href;break}}else b=c;b=b.replace(/^https?:\/\//,"http://");"strip"==this.a[a].www&&(b=b.replace(/^http:\/\/www\./,
"http://"));b=b.substr(0,250);this.c(a,"p",b)},F:function(a){for(var b=305419896,c=0;c<a.length;c++)b+=a.charCodeAt(c)*c;return b},M:function(a,b,c,d){var e=new Date;e.setTime(e.getTime()+1E3*c);document.cookie=a+"="+encodeURIComponent(b)+";expires="+e.toUTCString()+";path=/;domain="+d+";"},B:function(a){for(var b=document.cookie.split(";"),c=0;c<b.length;c++){var d=b[c].split("=");if(0<=d[0].indexOf(a))return decodeURIComponent(d[1])}return!1},R:function(a){return-1!==document.cookie.indexOf(a+"=")},
j:function(a){return"undefined"!==typeof a},L:function(a){var b=this,c=b.a[a],d=b.h+"/";try{"withCredentials"in new XMLHttpRequest?(x=new (window.XMLHttpRequest||ActiveXObject)("MSXML2.XMLHTTP.3.0"),x.open("GET",b.protocol+b.host+"/w/track/"+c.key+"/?"+b.C(a),!0),x.withCredentials=!0,x.onreadystatechange=function(){4===this.readyState&&200==this.status&&b.v(this.responseText,b,c,d)}):"undefined"!==typeof XDomainRequest&&(x=new window.XDomainRequest,x.open("GET",document.location.protocol+b.host+"/w/track/"+
c.key+"/?"+b.C(a),!0),x.onload=function(){b.v(x.responseText,b,c,d)}),x.send()}catch(e){}},v:function(a,b,c,d){try{var e=JSON.parse(a);"undefined"!=typeof e.w&&("sidebar"==e.w?b.m(function(){b.I(c,e.i,d,e.sp)}):"blank"!=e.w&&b.J(c,e.i,d));"undefined"!=typeof e.f&&1==e.f&&0==c.hide_feedback&&b.m(function(){b.H(b,c.key,e)});"undefined"!=typeof e.p&&setTimeout(function(){b.u(b,c,e.p)},e.p)}catch(l){}},u:function(a,b,c){(new Image(1,1)).src=a.protocol+a.host+"/w/track/"+b.key+"/?ping=1&z="+a.random();
setTimeout(function(){a.u(a,b,c)},c)},m:function(a){if("function"==typeof a){if(this.g.ready)return a();this.g.stack.push(a)}},A:function(){if(!this.g.ready){var a;if(/interactive|complete|loaded/.test(document.readyState))for(this.g.ready=!0;a=this.g.stack.shift();)a();else{var b=this;setTimeout(function(){b.A()},50)}}},H:function(a,b,c){if(a.a.fb_attached)return!1;a.a.fb_attached=!0;var d={key:b};d.font="undefined"!==typeof c.cf?c.cf:"#fafafa";d.background="undefined"!==typeof c.cb?c.cb:"#19a1d8";
b=document.createElement("a");b.setAttribute("id","trendcounter-feedback");b.style.cursor="pointer";b.style.display="block";b.style.height="35px";b.style.lineHeight="35px";b.style.textAlign="center";b.style.fontFamily="Helvetica,Arial,sans-serif";b.style.fontSize="13px";b.style.textDecoration="none";b.style.whiteSpace="nowrap";b.style.minWidth="86px";b.style.padding="0px 10px";b.style.position="fixed";b.style.bottom="0";b.style.right="5%";b.style.borderRadius="4px 4px 0 0";b.style.zIndex="9999999";
b.style.backgroundColor=d.background;b.style.color=d.font;b.onclick=function(){document.getElementById("trendcounter-feedback").style.display="none";a.K(a,d.key)};b.innerHTML='<svg style="vertical-align:text-bottom;" width="17px" height="17px" viewBox="0 0 1792 1792" xmlns="http://www.w3.org/2000/svg"><path d="M1792 896q0 174-120 321.5t-326 233-450 85.5q-70 0-145-8-198 175-460 242-49 14-114 22-17 2-30.5-9t-17.5-29v-1q-3-4-.5-12t2-10 4.5-9.5l6-9 7-8.5 8-9q7-8 31-34.5t34.5-38 31-39.5 32.5-51 27-59 26-76q-157-89-247.5-220t-90.5-281q0-130 71-248.5t191-204.5 286-136.5 348-50.5q244 0 450 85.5t326 233 120 321.5z" fill="'+
d.font+'"/></svg> Feedback';document.body.appendChild(b);window.addEventListener&&window.addEventListener("message",a.s,!1);window.attachEvent&&window.attachEvent("onmessage",a.s)},K:function(a,b){var c=document.createElement("div");c.setAttribute("id","tc-fb-wrapper");c.style.height="397px";c.style.width="100%";c.style.maxWidth="350px";c.style.background='url("https://s.tcimg.com/w/media/loader.gif") center center no-repeat #fff';c.style.position="fixed";c.style.bottom="15px";c.style.right="15px";
c.style.zIndex="9999999";c.style.boxShadow="0px 0px 7px rgba(0, 0, 0, 0.23)";c.style.overflow="hidden";var d=document.createElement("iframe");d.setAttribute("id","tc-fb-content");d.frameBorder="0";d.allowTransparency="true";d.backgroundColor="transparent";d.scrolling="no";d.style.width="100%";d.style.height="100%";d.src=a.h+"/client/"+b+"/feedback/?_="+this.random()+"&rx="+encodeURIComponent(window.location);c.appendChild(d);d=document.createElement("div");d.setAttribute("id","tc-fb-shim");d.style.cssText=
"background-color:#000; opacity: 0.3; filter:alpha(opacity=30); -moz-opacity: 0.3;left:0; position: fixed;top:0;bottom:0;right:0;width:100%;z-index:9999998";document.body.appendChild(d);document.body.appendChild(c);document.getElementById("tc-fb-shim").onclick=function(){a.s({data:"tc.close"})}},s:function(a){a=a.data.split("|");if("tc.close"==a[0])try{document.getElementById("tc-fb-wrapper").outerHTML="",document.getElementById("tc-fb-shim").outerHTML="",document.getElementById("trendcounter-feedback").style.display=
"block"}catch(b){}else"tc.update"==a[0]&&(document.getElementById("tc-fb-wrapper").style.height=a[1]+"px")},J:function(a,b,c){try{var d=document.getElementById("tc-"+a.key);null==d&&(d=document.querySelector("script[data-tc-id='"+a.key+"']"));element=document.createElement("a");element.href=c;element.target="_blank";element.innerHTML='<img src="data:image/png;base64,'+b+'" border="0" alt="trendcounter" title="'+a.title+'" />';d.parentNode.insertBefore(element,d.nextSibling)}catch(e){}},I:function(a,
b,c,d){var e=d.split("-");d=e[0];var e=e[1],f=45,g=94;if("top"==d||"bottom"==d)f=94,g=45;f="display:block !important;width: "+f+"px !important;height: "+g+"px !important;padding: 0;margin: 0;z-index: 9999999;cursor: pointer;bottom: 0;";if("top"==e||"bottom"==e)f+=e+": 15% !important;"+d+": -8px;";else if("middle"==e)f+="top: 40% !important;"+d+": -8px;";else if("center"==e)f+="margin-left: -47px !important;left: 50% !important;"+d+": -8px;";else if("right"==e||"left"==e)f+=e+": 15% !important;"+d+
": -8px;";e=document.createElement("div");e.title=a.title;f+='position: fixed;background-image:url("data:image/png;base64,'+b+'");background-repeat:no-repeat;';e.style.setAttribute?e.style.setAttribute("cssText",f):e.setAttribute("style",f);e.onmouseover=function(){this.style[d]="0"};e.onmouseout=function(){this.style[d]="-8px"};e.onclick=function(){window.open(c)};try{document.getElementsByTagName("body")[0].insertBefore(e,document.body.firstChild)}catch(n){}},o:function(a){var b={b:"default",action:a[0]};
0<a[0].indexOf(".")&&(a=a[0].split("."),b.b=a[0],b.action=a[1]);return b}};window._trendcounter={enableCookies:function(){f.a["default"].use_cookies=!0;f.a["default"].respect_dnt=!1;f.D("default")}};window._tcq.push=function(a){var b=f.o(a);"track"==b.action&&f.track(b.b,a)};try{for(var g=0;g<window._tcq.length;g++){var k=window._tcq[g],h=f.o(k);if("init"==h.action||"track"==h.action)"init"==h.action&&(f.G(),f.j(k[2])&&1!=k[2]||f.track(h.b,[])),"track"==h.action&&f.track(h.b,k)}}catch(a){}}})();
